[package]
name = "cargo-fetcher"
version = "0.5.1"
authors = ["Embark <opensource@embark-studios.com>", "Jake Shadle <jake.shadle@embark-studios.com>"]
edition = "2018"
description = "🎁 Experimental alternative to cargo fetch"
license = "MIT OR Apache-2.0"
documentation = "https://docs.rs/cargo-fetcher"
homepage = "https://github.com/EmbarkStudios/cargo-fetcher"
repository = "https://github.com/EmbarkStudios/cargo-fetcher"
keywords = ["fetch", "gcs", "s3"]
readme = "README.md"

[dependencies]
anyhow = "1.0.17"
bytes = "0.4.12"
chrono = "0.4.9"
app_dirs2 = "2.0.4"
env_logger = "0.7.1"
flate2 = { version = "1.0.12", default-features = false, features = ["rust_backend"] }
futures = { version = "0.1.29", optional = true}
http = "0.1.19"
log = "0.4.8"
rayon = "1.2.0"
remove_dir_all = "0.5.2"
reqwest = { version = "0.9.22", default-features = false, features = ["rustls-tls"] }
ring = "0.16.9"
rusoto_core = { version = "0.41.0", default-features = false, features = ["rustls"], optional = true }
rusoto_s3 = { version = "0.41.0", default-features = false, features = ["rustls"], optional = true }
serde = { version = "1.0.102", features = ["derive"] }
structopt = "0.3.3"
tame-gcs = { version = "0.5.1", optional = true }
tame-oauth = { version = "0.3.0", features = ["gcp"], optional = true }
tar = "0.4.26"
tempfile = "3.1.0"
toml = "0.5.3"
url = "2.1.0"
walkdir = "2.2.9"
zstd = "0.5.0+zstd.1.4.3"

[features]
default = []
gcs = ["tame-gcs", "tame-oauth"]
s3 = ["futures", "rusoto_core", "rusoto_s3"]
