targets = [
    { triple = "x86_64-unknown-linux-gnu" },
    { triple = "x86_64-apple-darwin" },
    { triple = "x86_64-pc-windows-msvc" },
    { triple = "x86_64-unknown-linux-musl" },
]

[advisories]
unmaintained = "deny"
ignore = [
    "RUSTSEC-2019-0031",
]

[bans]
multiple-versions = "deny"
deny = [
    # we never want a dependency on openssl due to all of the cross platform
    # issues it has, particularly on windows
    { name = "openssl" },
    { name = "openssl-sys" },

    # dirs is ridiculously heavyweight for what it does
    { name = "dirs-sys" },
]
skip = [
    # crossbeam et all use an outdated autocfg
    { name = "autocfg", version = "=0.1.7" },

    # rustls uses an old version of base64
    { name = "base64", version = "=0.10.1" },

    # mio-named-pipes brings in 2 versions of miow
    { name = "miow", version = "=0.2.1" },

    # chrono uses an old version of time
    { name = "time", version = "=0.1.42" },

    # too many things still use ancient (slow to compile!) versions of winapi
    { name = "winapi", version = "=0.2.8" },
]
skip-tree = [

]

[licenses]
unlicensed = "deny"
# We want really high confidence when inferring licenses from text
confidence-threshold = 0.92
allow = [
    "Apache-2.0",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "ISC",
    "MIT",
    "MPL-2.0",
    "OpenSSL",
    "Zlib",
]

[[licenses.clarify]]
name = "ring"
# SPDX considers OpenSSL to encompass both the OpenSSL and SSLeay licenses
# https://spdx.org/licenses/OpenSSL.html
# ISC - Both BoringSSL and ring use this for their new files
# MIT - "Files in third_party/ have their own licenses, as described therein. The MIT
# license, for third_party/fiat, which, unlike other third_party directories, is
# compiled into non-test libraries, is included below."
# OpenSSL - Obviously
expression = "ISC AND MIT AND OpenSSL"
license-files = [
    { path = "LICENSE", hash = 0xbd0eed23 },
]

[[licenses.clarify]]
name = "webpki"
expression = "ISC"
license-files = [
    { path = "LICENSE", hash = 0x001c7e6c },
]
