[bans]
multiple-versions = "deny"
deny = [
    # we never want a dependency on openssl due to all of the cross platform
    # issues it has, particularly on windows
    { name = "openssl" },
    { name = "openssl-sys" },

    # dirs is ridiculously heavyweight for what it does
    { name = "dirs-sys" },
]
skip = [
    # reqwest <= 0.19.21 doesn't feature gate cookies, which ends up
    # bringing in a metric fuckton of duplicates
    { name = "idna", version = "=0.1.5" },
    { name = "percent-encoding", version = "=1.0.1" },
    { name = "serde_urlencoded", version = "=0.5.5" },
    { name = "url", version = "=1.7.2" },

    # mio-named-pipes brings in 2 versions of miow
    { name = "miow", version = "=0.2.1" },

    # too many things still use ancient (slow to compile!) versions of winapi
    { name = "winapi", version = "=0.2.8" },

    # crossbeam-queue uses and old crossbeam-utils :facepalm:
    { name = "crossbeam-utils", version = "=0.6.6" },
]
skip-tree = [
    # uuid uses old rand
    { name = "rand", version = "=0.6.5" },

    # ring pulls in web-sys, which we don't use, and don't care about
    { name = "web-sys", version = "=0.3.31" },
]

[licenses]
unlicensed = "deny"
# We want really high confidence when inferring licenses from text
confidence-threshold = 0.92
allow = [
    "Apache-2.0",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "CC0-1.0",
    "ISC",
    "MIT",
    "MPL-2.0",
    "OpenSSL",
    "Zlib",
]

[[licenses.clarify]]
name = "ring"
# SPDX considers OpenSSL to encompass both the OpenSSL and SSLeay licenses
# https://spdx.org/licenses/OpenSSL.html
# ISC - Both BoringSSL and ring use this for their new files
# MIT - "Files in third_party/ have their own licenses, as described therein. The MIT
# license, for third_party/fiat, which, unlike other third_party directories, is
# compiled into non-test libraries, is included below."
# OpenSSL - Obviously
expression = "ISC AND MIT AND OpenSSL"
license-files = [
    { path = "LICENSE", hash = 0xbd0eed23 },
]

[[licenses.clarify]]
name = "webpki"
expression = "ISC"
license-files = [
    { path = "LICENSE", hash = 0x001c7e6c },
]
