targets = [
    { triple = "x86_64-unknown-linux-gnu" },
    { triple = "x86_64-apple-darwin" },
    { triple = "x86_64-pc-windows-msvc" },
    { triple = "x86_64-unknown-linux-musl" },
]

[advisories]
unmaintained = "deny"
ignore = [
    # spin is deprecated, but still used by rustls
    "RUSTSEC-2019-0031",
    # net2 is deprecated, but it's used by mio, which is still stuck on winapi
    # 0.2, so we'll just wait a few years for that to be updated
    "RUSTSEC-2020-0016",
]

[bans]
multiple-versions = "deny"
deny = [
    # we never want a dependency on openssl due to all of the cross platform
    # issues it has, particularly on windows
    { name = "openssl" },
    { name = "openssl-sys" },

    # dirs is ridiculously heavyweight for what it does...sigh rusoto
    #{ name = "dirs-sys" },
]
skip = [
    # clap still uses an old ansi_term
    { name = "ansi_term", version = "=0.11.0" },

    # mio-named-pipes brings in 2 versions of miow
    { name = "miow", version = "=0.2.1" },

    # chrono!? uses and old version of time
    { name = "time", version = "=0.1.43" },

    # too many things still use ancient (slow to compile!) versions of winapi
    { name = "winapi", version = "=0.2.8" },
]
skip-tree = [
    # azure_sdk_core uses an old version of rustls/hyper/tokio
    { name = "hyper-rustls", version = "0.20.0" },
]

[licenses]
unlicensed = "deny"
# We want really high confidence when inferring licenses from text
confidence-threshold = 0.92
allow = [
    "Apache-2.0",
    "BSD-3-Clause",
    "ISC",
    "MIT",
    "MPL-2.0",
    "OpenSSL",
    "Zlib",
]

[[licenses.clarify]]
name = "ring"
# SPDX considers OpenSSL to encompass both the OpenSSL and SSLeay licenses
# https://spdx.org/licenses/OpenSSL.html
# ISC - Both BoringSSL and ring use this for their new files
# MIT - "Files in third_party/ have their own licenses, as described therein. The MIT
# license, for third_party/fiat, which, unlike other third_party directories, is
# compiled into non-test libraries, is included below."
# OpenSSL - Obviously
expression = "ISC AND MIT AND OpenSSL"
license-files = [
    { path = "LICENSE", hash = 0xbd0eed23 },
]

[[licenses.clarify]]
name = "webpki"
expression = "ISC"
license-files = [
    { path = "LICENSE", hash = 0x001c7e6c },
]
